version: "3.9"
services: 
  database:
    container_name: quote_database
    image: mariadb
    environment: 
      - MYSQL_DATABASE=quote
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456